name: packaging-and-releasing
on:
  push:
    branches:
      - 1.[0-9]+.[0-9]+
      - github_actions
jobs:
  packaging-and-releasing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: python3 -m pip install --upgrade build
      - run: python3 -m build
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
  test:
    runs-on: ubuntu-latest
    needs: packaging-and-releasing
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: python -m unittest discover

