name: packaging-and-releasing
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - 0.[0-9]+.[0-9]+
jobs:
  packaging-and-releasing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sed -r 's/(.*)(version=)(.*.)([0-9]+)(.*)/echo "\1\2\3$((\4+1))\5"/ge' setup.py > setup.py.tmp && mv setup.py.tmp setup.py
      - run: python3 -m pip install --upgrade build
      - run: python3 -m build
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
