name: packaging-and-releasing
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - 0.[0-9]+.[0-9]+
jobs:
  packaging-and-releasing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: python3 -m pip install --upgrade build
      - run: pip install yolk3
      - run: VERSION=$(yolk -V skillcorner | awk '{print $2}' | sed -r 's/([0-9]+).([0-9]+).([0-9]+)/echo "\1.\2.$((\3+1))"/ge')
      - run: sed -r -i "s/(.*version=.*)([0-9]+.[0-9]+.[0-9]+)(.*)/\1$VERSION\3/g" setup.py
      - run: python3 -m build
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
