name: packaging-and-releasing
on:
  push:
    branches:
      - v1.[0-9]+.[0-9]+
jobs:
  test-packaging-and-releasing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo 'Hello GitHub actions'
      - run: pwd
      - run: python -m unittest discover .
