name: packaging-and-releasing
on:
  push:
    branches:
      - 1.[0-9]+.[0-9]+
      - github_actions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: python -m unittest discover pipelines
  packaging-and-releasing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: python3 -m pip install --upgrade build
        - run: python3 -m build
        - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
         repository_url: https://github.com/jpatacz/pipelines_test
