name: packaging-and-releasing
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  packaging-and-releasing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Check current branch
        id: check-branch
        run: |
          if [[ ${{ github.head_ref }} =~ ^.*[0-9]+.[0-9]+.0$ ]]; then
              echo ::set-output name=match::true
          fi

      - name: Check condition
        run: echo ${{ steps.check-branch.outputs.match }}

      - name: Edit version
        if: steps.check-branch.outputs.match == 'true'
        run: sed -r -i 's/(.*)(version=.*)([0-9]+).([0-9]+).([0-9]+)(.*)/echo "\1\2\3.\4.$((\5+1))\6"/ge' setup.py

      - name: Commit changes
        if: steps.check-branch.outputs.match == 'true'
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Incrementing patch version in setup.py'
          add: 'setup.py'

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Display setup.py
        if: steps.check-branch.outputs.match == 'true'
        run: cat setup.py

      - name: Install build
        run: python3 -m pip install --upgrade build

      - name: Build package
        run: python3 -m build

      - name: Release package
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://pypi.org/legacy/
