name: packaging-and-releasing
on:
  push:
    branches:
      - github_actions
jobs:
  test-packaging-and-releasing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo 'Hello GitHub actions'
