name: testing
on:
  pull_request:
    types:
      - closed
    branches-ignore:
      - 0.[0-9]+.[0-9]+
      - master
  push:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: python -m unittest discover
