name: testing
on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: python -m unittest discover
  condition:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Check current branch
      run: echo ${{github.ref}}

    - name: Check condition
      run: echo ${{ !contains(github.ref, r'[0-9]+.3.0') }}

    - name: Edit version
      run: sed -r -i 's/(.*)(version=.*)([0-9]+).([0-9]+).([0-9]+)(.*)/echo "\1\2\3.\4.$((\5+1))\6"/ge' setup.py
      if: ${{ !contains(github.ref, r'[0-9]+.3.0') }}