name: testing
on:
  [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: python -m unittest discover
      - uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          channel: '@Julia Patacz'
        if: always()

  condition:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Check current branch
      id: check-branch
      run: |
        if [[ ${{ github.ref }} =~ ^.*[0-9]+.[0-9]+.0$ ]]; then
            echo ::set-output name=match::true
        fi

    - name: Check condition
      run: echo ${{ steps.check-branch.outputs.match }}

    - name: Edit version
      if: steps.check-branch.outputs.match == 'true'
      run: sed -r -i 's/(.*)(version=.*)([0-9]+).([0-9]+).([0-9]+)(.*)/echo "\1\2\3.\4.$((\5+1))\6"/ge' setup.py

    - name: Edit version
      if: steps.check-branch.outputs.match == 'true'
      run: sed -r -i 's/(.*)(version=.*)([0-9]+).([0-9]+).([0-9]+)(.*)/echo "\1\2\3.\4.$((\5+1))\6"/ge' setup.py
